server:
  port: 8166
  servlet:
    context-path: /web-market-cart
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cloud-postgres
    password: cloud-postgres
    url: jdbc:postgresql://192.168.99.101:5432/cloud-postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: update

    show-sql: true
    generate-ddl: true
    database: postgresql
utils:
  cart:
    prefix: SPRING_WEB_
integration:
  core-service:
    url: http://localhost:5555/core
  analytic-service:
    url: http://localhost:5555/analytic

